# Generated by Django 3.2.9 on 2021-11-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('form_obj_name', models.CharField(max_length=255)),
                ('func_obj_name', models.CharField(max_length=255)),
            ],
        ),
    ]
