# Generated by Django 3.2.9 on 2021-12-06 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_basescript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseScript',
        ),
    ]
