services:
  web:
    build: ./site
    container_name: snmprogs_web
    volumes:
      - ./site:/app
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
  osrm:
    image: osrm/osrm-backend:latest
    container_name: snmprogs_osrm
    restart: unless-stopped
    volumes:
      - ./osrm:/data
    command: >
      sh -c "
      if [ ! -f /data/map.osrm ]; then
        echo '=== Выполняем osrm-extract ===' &&
        osrm-extract -p /opt/car.lua /data/map.osm.pbf &&
        echo '=== Выполняем osrm-partition ===' &&
        osrm-partition /data/map.osrm &&
        echo '=== Выполняем osrm-customize ===' &&
        osrm-customize /data/map.osrm &&
        echo '=== Обработка завершена ===';
      fi &&
      echo '=== Запускаем OSRM-сервер ===' &&
      osrm-routed --algorithm mld /data/map.osrm
      "
volumes:
  static_volume:
  media_volume: