services:
  db:
    image: postgres:14
    container_name: snmprogs_db
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
  redis:
    image: redis:7
    container_name: snmprogs_redis
    restart: unless-stopped
  web:
    build: ./site
    container_name: snmprogs_web
    volumes:
      - ./site:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: unless-stopped
  celery:
    build: ./site
    container_name: snmprogs_celery
    volumes:
      - ./site:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
      - redis
      - web
    env_file:
      - .env
    environment:
      - DJANGO_SERVER_TYPE=celery
    restart: unless-stopped
  osrm:
    image: osrm/osrm-backend:latest
    container_name: snmprogs_osrm
    restart: unless-stopped
    volumes:
      - ./osrm:/data
    command: >
      sh -c "
      if [ ! -f /data/map.osrm ]; then
        echo '=== Выполняем osrm-extract ===' &&
        osrm-extract -p /opt/car.lua /data/map.osm.pbf &&
        echo '=== Выполняем osrm-partition ===' &&
        osrm-partition /data/map.osrm &&
        echo '=== Выполняем osrm-customize ===' &&
        osrm-customize /data/map.osrm &&
        echo '=== Обработка завершена ===';
      fi &&
      echo '=== Запускаем OSRM-сервер ===' &&
      osrm-routed --algorithm mld /data/map.osrm
      "
volumes:
  postgres_volume:
  static_volume:
  media_volume: