# Generated by Django 6.0.3 on 2026-03-25 12:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yandex_geocoder', '0003_delete_yandexgeocodersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoutingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traffic_factor', models.FloatField(default=0.3, help_text='Система не учитывает пробки. Для получения картины более приближенной к реальности             время между двумя точками рассчитывается по формуле: time * (1 + traffic_factor)', verbose_name='Коэффициент трафика')),
                ('start_service_time', models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Время необходимое на погрузку товаров на производстве', verbose_name='Время на погрузку')),
                ('order_service_time', models.DurationField(default=datetime.timedelta(seconds=900), help_text='Время необходимое на передачу заказа (парковка, лифт...)', verbose_name='Время на каждый заказ')),
                ('max_waiting_time', models.DurationField(default=datetime.timedelta(seconds=86340), help_text='Менять этот парамер нужно с ОСТОРОЖНОСТЬЮ. слишком маленькое значение может привести к неразрешимым конфликтам', verbose_name='Максимальное время простоя курьера')),
                ('max_time', models.DurationField(default=datetime.timedelta(seconds=86340), help_text='Курьер НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ не может закончить позже этого врмени', verbose_name='Максимальное время прибытия в конечную точку')),
                ('start_work_time', models.DurationField(default=datetime.timedelta(seconds=21600), help_text='При начале работы курьера раньше этого времени, будет назначаться штраф', verbose_name='Время начала работы курьера (и производства)')),
                ('end_work_time', models.DurationField(default=datetime.timedelta(seconds=86340), help_text='При окончании работы курьера позже этого времени, будет назначаться штраф', verbose_name='Время окончания работы курьера')),
                ('work_hours', models.DurationField(default=datetime.timedelta(seconds=28800), help_text='При превышении общего времени работы курьера, будет назначаться штраф', verbose_name='Рабочие часы курьера')),
                ('max_late', models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Максимально возможное отклонение времени прибытия к заказу от назначенного интервала', verbose_name='Максимальное время опоздания к заказу')),
                ('late_penalty', models.IntegerField(default=1000, help_text='Штраф решению за каждую секунду отклонения времени прибытия к заказу от назначенного инревала', verbose_name='Штраф за опоздание')),
                ('exceed_work_hours_penalty', models.IntegerField(default=100, help_text='Штраф решению за каждую секунду превышения рабочих часов', verbose_name='Штраф за превышение рабочих часов')),
                ('exceed_work_time_penalty', models.IntegerField(default=100, help_text='Штраф решению за каждую секунду отклонения времени работы курьера от рабочего времени', verbose_name='Штраф за выход из рабочего времени')),
                ('exceed_capacity_penalty', models.IntegerField(default=10000, help_text='Штраф решению за каждый грамм превышения вместимости курьера', verbose_name='Штраф за превышение вместимости')),
                ('max_process_time', models.DurationField(default=datetime.timedelta(seconds=300), help_text='Система выдаст наилучший маршрут который смогла найти за предоставленное время', verbose_name='Максимальное время обработки маршрутов')),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_geocoder.location', verbose_name='Локация склада')),
            ],
            options={
                'verbose_name': 'Настройки маршрутизации курьеров',
                'verbose_name_plural': 'Настройки маршрутизации курьеров',
                'permissions': [('can_make_delivery_routing', 'Может создавать маршруты курьеров')],
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (кг)')),
                ('home_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yandex_geocoder.location', verbose_name='Локация дом')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='delivery_distributor.deliveryroutingsettings')),
            ],
        ),
    ]
