# Generated by Django 6.0.3 on 2026-03-25 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_distributor', '0003_alter_courier_home_location'),
        ('yandex_geocoder', '0003_delete_yandexgeocodersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='home_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='yandex_geocoder.location', verbose_name='Локация дом'),
        ),
    ]
