# Generated by Django 6.0.3 on 2026-03-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_distributor', '0004_alter_courier_home_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroutingsettings',
            name='slack_penalty',
            field=models.IntegerField(default=10, help_text='Штраф решению за каждую секунду простоя курьера', verbose_name='Штраф за простой'),
        ),
    ]
