# Generated by Django 6.0.3 on 2026-03-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_distributor', '0005_deliveryroutingsettings_slack_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroutingsettings',
            name='fuel_factor',
            field=models.FloatField(default=10, help_text='Расход топлива на 1л/100 км', verbose_name='Расход топлива'),
        ),
    ]
