# Generated by Django 6.0.3 on 2026-03-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_distributor', '0006_deliveryroutingsettings_fuel_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroutingsettings',
            name='vehicle_start_cost',
            field=models.IntegerField(default=10000, help_text='Используется для избегания коротких маршрутов', verbose_name='Стоимость использования одной машины'),
        ),
        migrations.AlterField(
            model_name='deliveryroutingsettings',
            name='fuel_factor',
            field=models.FloatField(default=10, help_text='Расход топлива на л/100 км', verbose_name='Расход топлива'),
        ),
    ]
