# Generated by Django 6.0.3 on 2026-03-25 17:19

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_distributor', '0007_deliveryroutingsettings_vehicle_start_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='color',
            field=colorful.fields.RGBColorField(colors=['#82cdff', '#1e98ff', '#177bc9', '#0e4779', '#ffd21e', '#ff931e', '#e6761b', '#ed4543', '#56db40', '#1bad03', '#97a100', '#595959', '#b3b3b3', '#f371d1', '#b51eff', '#793d0e'], default='#000000', verbose_name='Цвет на карте'),
        ),
        migrations.AddField(
            model_name='courier',
            name='project',
            field=models.CharField(blank=True, max_length=255, verbose_name='Проект в МС'),
        ),
    ]
