# Generated by Django 6.0.3 on 2026-03-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_distributor', '0008_courier_color_courier_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroutingsettings',
            name='fuel_penalty',
            field=models.IntegerField(default=100, help_text='Штраф решению за каждый грамм израсходованного топлива', verbose_name='Штраф на расход топлива'),
        ),
    ]
