# Generated by Django 6.0.3 on 2026-03-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_distributor', '0009_deliveryroutingsettings_fuel_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryroutingsettings',
            name='balance_penalty',
            field=models.IntegerField(default=1000, help_text='Штраф к решению за разницу между минимальным и максимальным количеством заказов у курьеров', verbose_name='Штраф за дисбаланс кличества заказов'),
        ),
    ]
