# Generated by Django 6.0.3 on 2026-03-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YandexGeocoderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(blank=True, max_length=255, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Настройки Яндекс геокодера',
                'verbose_name_plural': 'Настройки Яндекс геокодера',
            },
        ),
    ]
