# Generated by Django 6.0.3 on 2026-03-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_geocoder', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YandexGeocoderSettings',
        ),
    ]
