# Generated by Django 6.0.3 on 2026-04-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInCreatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_state', models.CharField(blank=True, max_length=255, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Настройки создания входящих платежей',
                'verbose_name_plural': 'Настройки создания входящих платежей',
                'permissions': [('can_create_paymentin', 'Может создавать входящие платежи')],
            },
        ),
    ]
