# Generated by Django 6.0.3 on 2026-04-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentin_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentincreatorsettings',
            name='paymentin_state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус создаваемого входящего платежа'),
        ),
        migrations.AlterField(
            model_name='paymentincreatorsettings',
            name='order_state',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус заказа по умолчанию'),
        ),
    ]
