[pytest]
# addopts = --reuse-db --nomigrations
DJANGO_SETTINGS_MODULE = snmprogs.settings
python_files = tests.py test_*.py *_tests.py
norecursedirs = .git venv .venv env .env __pycache__ .pytest_cache .mypy_cache .idea .vscode