# Generated by Django 3.2.9 on 2026-03-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_map_loader', '0002_alter_paletteitem_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymappalettesettings',
            options={'permissions': [('can_load_delivery_map', 'Может загружать карту доставки')], 'verbose_name': 'Настройки палитры для выгрузки карты доставки', 'verbose_name_plural': 'Настройки палитры для выгрузки карты доставки'},
        ),
    ]
