# Generated by Django 6.0.3 on 2026-03-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_map_loader', '0003_alter_deliverymappalettesettings_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymappalettesettings',
            name='delivery_order_attribute_name',
        ),
    ]
