# Generated by Django 3.2.25 on 2026-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoySkladSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Настройки Мой Склад',
                'verbose_name_plural': 'Настройки Мой Склад',
            },
        ),
    ]
