# Generated by Django 3.2.9 on 2026-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moy_sklad_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moyskladsettings',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, verbose_name='Токен'),
        ),
    ]
