# Generated by Django 6.0.3 on 2026-03-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moy_sklad_settings', '0002_alter_moyskladsettings_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyskladsettings',
            name='delivery_order_attribute_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название атрибута очередности доставки'),
        ),
    ]
