# Generated by Django 6.0.3 on 2026-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moy_sklad_settings', '0003_moyskladsettings_delivery_order_attribute_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyskladsettings',
            name='delivery_time_attribute_name',
            field=models.CharField(blank=True, help_text='Дополнительное поле заказа покупателя', max_length=255, verbose_name='Название дополнительного поля времени доставки'),
        ),
        migrations.AlterField(
            model_name='moyskladsettings',
            name='delivery_order_attribute_name',
            field=models.CharField(blank=True, help_text='Дополнительное поле заказа покупателя', max_length=255, verbose_name='Название дополнительного поля очередности доставки'),
        ),
    ]
