# Generated by Django 6.0.3 on 2026-03-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moy_sklad_settings', '0004_moyskladsettings_delivery_time_attribute_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moyskladsettings',
            name='project_blacklist_for_delivery_routing',
            field=models.JSONField(blank=True, default=list, help_text='Заказы покупателья с этими проектами не попадают в маршрутизацию', verbose_name='Черный список проектов для маршрутизации коурьеров'),
        ),
    ]
