# Generated by Django 6.0.3 on 2026-03-31 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moy_sklad_settings', '0005_moyskladsettings_project_blacklist_for_delivery_routing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moyskladsettings',
            name='project_blacklist_for_delivery_routing',
        ),
        migrations.CreateModel(
            name='BlacklistProjectMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_blacklist_for_delivery_routing', to='moy_sklad_settings.moyskladsettings')),
            ],
            options={
                'verbose_name': 'Проект МС',
                'verbose_name_plural': 'Черный список проектов для маршрутизации курьеров',
            },
        ),
    ]
