# Generated by Django 3.2.9 on 2026-03-17 16:48

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMapPaletteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_order_attribute_name', models.CharField(blank=True, max_length=255, verbose_name='Название атрибута очередности доставки')),
            ],
            options={
                'verbose_name': 'Настройки палитры для выгрузки карты доставки',
                'verbose_name_plural': 'Настройки палитры для выгрузки карты доставки',
            },
        ),
        migrations.CreateModel(
            name='PaletteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorful.fields.RGBColorField(verbose_name='Цвет')),
                ('project', models.CharField(blank=True, max_length=255, verbose_name='Проект')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_by_color', to='delivery_map_loader.deliverymappalettesettings')),
            ],
            options={
                'ordering': ['color'],
                'unique_together': {('config', 'color', 'project')},
            },
        ),
    ]
