# Generated by Django 3.2.9 on 2026-03-18 18:39

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_map_loader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paletteitem',
            name='color',
            field=colorful.fields.RGBColorField(colors=['#82cdff', '#1e98ff', '#177bc9', '#0e4779', '#ffd21e', '#ff931e', '#e6761b', '#ed4543', '#56db40', '#1bad03', '#97a100', '#595959', '#b3b3b3', '#f371d1', '#b51eff', '#793d0e'], verbose_name='Цвет'),
        ),
    ]
