# Generated by Django 3.2.9 on 2026-03-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_map_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverymapgeneratorsettings',
            old_name='blacklist_dict',
            new_name='project_blacklist_dict',
        ),
    ]
