# Generated by Django 3.2.9 on 2026-03-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandCreatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_blacklist_dict', models.CharField(blank=True, max_length=255, verbose_name='Справочник с черным списком проектов')),
            ],
            options={
                'verbose_name': 'Настройки создания отгрузок',
                'verbose_name_plural': 'Настройки создания отгрузок',
            },
        ),
    ]
