# Generated by Django 3.2.9 on 2026-03-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demand_creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demandcreatorsettings',
            options={'permissions': [('can_create_demand', 'Может создавать отгрузки')], 'verbose_name': 'Настройки создания отгрузок', 'verbose_name_plural': 'Настройки создания отгрузок'},
        ),
    ]
