# Generated by Django 3.2.9 on 2026-03-17 16:18

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMapGeneratorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklist_dict', models.CharField(blank=True, max_length=255, verbose_name='Справочник с черным списком проектов')),
                ('yandexmaps_key', models.CharField(blank=True, max_length=255, verbose_name='Ключ Яндекс.Карт')),
                ('default_color', colorful.fields.RGBColorField(blank=True, verbose_name='Цвет по умолчанию')),
                ('delivery_time_missed_color', colorful.fields.RGBColorField(blank=True, verbose_name='Цвет для пропущенного времени отгрузки')),
            ],
            options={
                'verbose_name': 'Настройки создания карты доставки',
                'verbose_name_plural': 'Настройки создания карты доставки',
            },
        ),
    ]
