# Generated by Django 3.2.9 on 2026-03-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_map_creator', '0002_rename_blacklist_dict_deliverymapgeneratorsettings_project_blacklist_dict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymapgeneratorsettings',
            options={'permissions': [('can_generate_delivery_map', 'Может создавать карту доставки')], 'verbose_name': 'Настройки создания карты доставки', 'verbose_name_plural': 'Настройки создания карты доставки'},
        ),
    ]
