# Generated by Django 3.2.9 on 2026-03-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsSyncronizeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='Название организации')),
                ('states_and_accounts_dict', models.CharField(blank=True, max_length=255, verbose_name='Словарь соответствия статусов и счетов')),
            ],
            options={
                'verbose_name': 'Настройки синхорнизации счетов',
                'verbose_name_plural': 'Настройки синхорнизации счетов',
            },
        ),
    ]
