# Generated by Django 3.2.9 on 2026-03-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_synchronize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountssyncronizesettings',
            name='states_and_accounts_dict',
            field=models.CharField(blank=True, max_length=255, verbose_name='Справочник соответствия статусов и счетов'),
        ),
    ]
