# Generated by Django 3.2.9 on 2026-03-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_synchronize', '0002_alter_accountssyncronizesettings_states_and_accounts_dict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountssyncronizesettings',
            options={'permissions': [('can_syncronize_accounts', 'Может синхронизировать счета')], 'verbose_name': 'Настройки синхорнизации счетов', 'verbose_name_plural': 'Настройки синхорнизации счетов'},
        ),
    ]
