# Generated by Django 6.0.3 on 2026-03-21 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=512, unique=True, verbose_name='Адрес')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRoutingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivey_distributor.location', verbose_name='Локация склада')),
            ],
            options={
                'verbose_name': 'Настройки маршрутизации курьеров',
                'verbose_name_plural': 'Настройки маршрутизации курьеров',
                'permissions': [('can_make_delivery_routing', 'Может создавать маршруты курьеров')],
            },
        ),
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость (кг)')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couriers', to='delivey_distributor.deliveryroutingsettings')),
                ('home_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivey_distributor.location', verbose_name='Локация дом')),
            ],
        ),
    ]
