# Generated by Django 6.0.3 on 2026-03-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivey_distributor', '0002_alter_location_options_alter_courier_name'),
        ('yandex_geocoder', '0002_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryroutingsettings',
            name='store_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_geocoder.location', verbose_name='Локация склада'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='home_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yandex_geocoder.location', verbose_name='Локация дом'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
