# Generated by Django 3.2.9 on 2026-03-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing_creator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processingcreatorsettings',
            old_name='processing_plan_blacklist_entity',
            new_name='processing_plan_blacklist_dict',
        ),
    ]
