# Generated by Django 6.0.3 on 2026-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivey_distributor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterField(
            model_name='courier',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя'),
        ),
    ]
