# Generated by Django 3.2.9 on 2026-03-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingCreatorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_plan_blacklist_entity', models.CharField(blank=True, max_length=255, verbose_name='Справочник c черным списком техкарт для автоматического производства')),
                ('store_name', models.CharField(blank=True, max_length=255, verbose_name='Склад')),
            ],
            options={
                'verbose_name': 'Настройки создания тех.операций',
                'verbose_name_plural': 'Настройки создания тех.операций',
            },
        ),
    ]
