# Generated by Django 3.2.9 on 2026-03-18 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing_creator', '0002_rename_processing_plan_blacklist_entity_processingcreatorsettings_processing_plan_blacklist_dict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processingcreatorsettings',
            options={'permissions': [('can_create_processing', 'Может создавать тех.операции')], 'verbose_name': 'Настройки создания тех.операций', 'verbose_name_plural': 'Настройки создания тех.операций'},
        ),
    ]
