# Generated by Django 6.0.3 on 2026-03-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDataLoaderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_load_courier_data', 'Может загружать данные курьеров'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
